from app.models import db, Image

def seed_images():
    images = [
        {
            "url":"https://empirebnb.s3.us-east-2.amazonaws.com/6848+/001.jpeg",
            "listing_id":1
        },
        {
            "url":"https://empirebnb.s3.us-east-2.amazonaws.com/6848+/002.jpeg",
            "listing_id":1
        },
        {
            "url":"https://empirebnb.s3.us-east-2.amazonaws.com/6848+/003.jpeg",
            "listing_id":1
        },
        {
            "url":"https://empirebnb.s3.us-east-2.amazonaws.com/6848+/004.jpeg",
            "listing_id":1
        },
        {
            "url":"https://empirebnb.s3.us-east-2.amazonaws.com/6848+/005.jpeg",
            "listing_id":1
        },
        {
            "url":"https://empirebnb.s3.us-east-2.amazonaws.com/6848+/006.jpeg",
            "listing_id":1
        },
        {
            "url":"https://empirebnb.s3.us-east-2.amazonaws.com/7322/001.jpeg",
            "listing_id":2
        },
        {
            "url":"https://empirebnb.s3.us-east-2.amazonaws.com/7322/002.jpeg",
            "listing_id":2
        },
        {
            "url":"https://empirebnb.s3.us-east-2.amazonaws.com/7322/003.jpeg",
            "listing_id":2
        },
        {
            "url":"https://empirebnb.s3.us-east-2.amazonaws.com/7322/004.jpeg",
            "listing_id":2
        },
        {
            "url":"https://empirebnb.s3.us-east-2.amazonaws.com/7322/005.jpeg",
            "listing_id":2
        },
        {
            "url":"https://empirebnb.s3.us-east-2.amazonaws.com/7322/006.jpeg",
            "listing_id":2
        },
        {
            "url":"https://empirebnb.s3.us-east-2.amazonaws.com/2595/001.jpeg",
            "listing_id":3
        },
        {
            "url":"https://empirebnb.s3.us-east-2.amazonaws.com/2595/002.jpeg",
            "listing_id":3
        },
        {
            "url":"https://empirebnb.s3.us-east-2.amazonaws.com/2595/003.jpeg",
            "listing_id":3
        },
        {
            "url":"https://empirebnb.s3.us-east-2.amazonaws.com/2595/004.jpeg",
            "listing_id":3
        },
        {
            "url":"https://empirebnb.s3.us-east-2.amazonaws.com/2595/005.jpeg",
            "listing_id":3
        },
        {
            "url":"https://empirebnb.s3.us-east-2.amazonaws.com/12937/001.jpeg",
            "listing_id":4
        },
        {
            "url":"https://empirebnb.s3.us-east-2.amazonaws.com/12937/002.jpeg",
            "listing_id":4
        },
        {
            "url":"https://empirebnb.s3.us-east-2.amazonaws.com/12937/003.jpeg",
            "listing_id":4
        },
        {
            "url":"https://empirebnb.s3.us-east-2.amazonaws.com/12937/004.jpeg",
            "listing_id":4
        },
        {
            "url":"https://empirebnb.s3.us-east-2.amazonaws.com/12937/005.jpeg",
            "listing_id":4
        },
        {
            "url":"https://empirebnb.s3.us-east-2.amazonaws.com/18152/001.jpeg",
            "listing_id":5
        },
        {
            "url":"https://empirebnb.s3.us-east-2.amazonaws.com/18152/002.jpeg",
            "listing_id":5
        },
        {
            "url":"https://empirebnb.s3.us-east-2.amazonaws.com/18152/003.jpeg",
            "listing_id":5
        },
        {
            "url":"https://empirebnb.s3.us-east-2.amazonaws.com/18152/004.jpeg",
            "listing_id":5
        },
        {
            "url":"https://empirebnb.s3.us-east-2.amazonaws.com/18152/005.jpeg",
            "listing_id":5
        },
        {
            "url":"https://empirebnb.s3.us-east-2.amazonaws.com/18152/006.jpeg",
            "listing_id":5
        },
        {
            "url":"https://empirebnb.s3.us-east-2.amazonaws.com/20853/001.jpeg",
            "listing_id":6
        },
        {
            "url":"https://empirebnb.s3.us-east-2.amazonaws.com/20853/002.jpeg",
            "listing_id":6
        },
        {
            "url":"https://empirebnb.s3.us-east-2.amazonaws.com/20853/003.jpeg",
            "listing_id":6
        },
        {
            "url":"https://empirebnb.s3.us-east-2.amazonaws.com/20853/004.jpeg",
            "listing_id":6
        },
        {
            "url":"https://empirebnb.s3.us-east-2.amazonaws.com/20853/005.jpeg",
            "listing_id":6
        },
        {
            "url":"https://empirebnb.s3.us-east-2.amazonaws.com/20853/006.jpeg",
            "listing_id":6
        }
    ]

    for image in images:
        new_image = Image(
            url = image['url'],
            listing_id = image['listing_id'],
        )

        db.session.add(new_image)
        db.session.commit()


def undo_images():
    db.session.execute('TRUNCATE images RESTART IDENTITY CASCADE;')
    db.session.commit()
